
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class Pertemuan_6 extends javax.swing.JFrame {
String keranjangPesanan =" ";
int totalHarga = 0;
    private String isiPesanan;
    /**
     * Creates new form Pertemuan_6
     */
    public Pertemuan_6() {
        initComponents();
        
        dropdown_kategori.removeAllItems();
        dropdown_kategori.addItem("Makanan");
        dropdown_kategori.addItem("Minuman");
        dropdown_kategori.addItem("Snacks");
        
    }
    public static void main(String[] args){
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                new Pertemuan_6().setVisible(true);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        no_meja_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pesan_field = new javax.swing.JTextField();
        dropdown_kategori = new javax.swing.JComboBox<>();
        pesan_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_menu = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jumlah_field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        harga_field = new javax.swing.JTextField();
        btn_total = new javax.swing.JButton();
        total_field = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        keranjang_field = new javax.swing.JTextArea();
        btn_reset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel1.setText("APLIKASI PEMESANAN MAKANAN");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel2.setText("No. Meja :");

        no_meja_field.setBackground(new java.awt.Color(204, 204, 204));
        no_meja_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        no_meja_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_meja_fieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel3.setText("Pemesan  :");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel4.setText("Kategori :");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel5.setText("Menu :");

        pesan_field.setBackground(new java.awt.Color(204, 204, 204));
        pesan_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pesan_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan_fieldActionPerformed(evt);
            }
        });

        dropdown_kategori.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        dropdown_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        dropdown_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_kategoriActionPerformed(evt);
            }
        });

        pesan_button.setBackground(new java.awt.Color(102, 102, 102));
        pesan_button.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        pesan_button.setForeground(new java.awt.Color(255, 255, 255));
        pesan_button.setText("Pesan");
        pesan_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pesan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan_buttonActionPerformed(evt);
            }
        });

        list_menu.setBorder(null);
        list_menu.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        list_menu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Menu 1", "Menu 2", "Menu 3", "Menu 4", "Menu 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_menu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_menuValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_menu);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel8.setText("Jumah Pesanan :");

        jumlah_field.setBackground(new java.awt.Color(204, 204, 204));
        jumlah_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel10.setText("Harga :");

        harga_field.setBackground(new java.awt.Color(204, 204, 204));
        harga_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        harga_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_fieldActionPerformed(evt);
            }
        });

        btn_total.setBackground(new java.awt.Color(102, 102, 102));
        btn_total.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        btn_total.setForeground(new java.awt.Color(255, 255, 255));
        btn_total.setText("Total :");
        btn_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_totalActionPerformed(evt);
            }
        });

        total_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        total_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_fieldActionPerformed(evt);
            }
        });

        keranjang_field.setEditable(false);
        keranjang_field.setBackground(new java.awt.Color(255, 255, 255));
        keranjang_field.setColumns(20);
        keranjang_field.setRows(5);
        keranjang_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(keranjang_field);

        btn_reset.setBackground(new java.awt.Color(204, 204, 204));
        btn_reset.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel6.setText("Detail Pesanan :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(25, 25, 25))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jumlah_field, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(harga_field)
                                    .addComponent(total_field)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(26, 26, 26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(no_meja_field, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pesan_field, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1)
                                    .addComponent(dropdown_kategori, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(pesan_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(no_meja_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(pesan_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(dropdown_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jumlah_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(harga_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_total, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(total_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pesan_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void no_meja_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_meja_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_meja_fieldActionPerformed

    private void pesan_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesan_fieldActionPerformed

    private void pesan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan_buttonActionPerformed
        String nomorMeja=no_meja_field.getText();
        String namaPemesan=pesan_field.getText();
        String keranjangPesanan=keranjang_field.getText();
        String total=total_field.getText();
        
        if (nomorMeja.isEmpty()|| namaPemesan.isEmpty()|| keranjangPesanan.isEmpty()|| total.isEmpty()){
            JOptionPane.showMessageDialog(this, "Lengkapi identitas dan pastikan keranjang tidak kosong");
            return;
        }
        String gabung= """
                       === DETAIL PESANAN ===
                       No Meja : """+nomorMeja+"\nNama Pemesan : "+namaPemesan+"\nPesanan : "+keranjangPesanan+"\nTotal Bayar : "+total;
        JOptionPane.showMessageDialog(this,gabung );
    }//GEN-LAST:event_pesan_buttonActionPerformed

    private void dropdown_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_kategoriActionPerformed
        String kategori=dropdown_kategori.getSelectedItem().toString();
        String[]data = null;
        if(kategori.equals("Makanan")){
            data = new String[]{"Bakso","Nasi Goreng Spesial","Ayam Lada Hitam","Ayam BBQ","Ayam Mentega"};
        }
        else if(kategori.equals("Minuman")){
            data = new String[]{"Americano","Cappucino", "Lemon Tea","Lemon","Matcha Latte"};
        }
        else if(kategori.equals("Snacks")){
            data = new String[]{"Dimsum","Churros","Sweet Corn","Salad Buah"};
        }
        list_menu.setListData(data);

        
    }//GEN-LAST:event_dropdown_kategoriActionPerformed

    private void list_menuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_menuValueChanged
        String menu=list_menu.getSelectedValue();
        if (menu !=null){
            int harga = 0;
            switch (menu.toLowerCase()){
                case "bakso": harga = 15000; break;
                case "nasi goreng spesial": harga = 20000; break;
                case "ayam lada hitam": harga = 25000; break;
                case "ayam bbq": harga = 24000; break;
                case "ayam mentega": harga = 24000; break;
                case "americano": harga = 15000; break;
                case "cappucino": harga = 13000; break;
                case "lemon tea": harga = 12000; break;
                case "lemon": harga = 12000; break;                
                case "matcha latte": harga = 12000; break;
                case "dimsum": harga = 20000; break;
                case "churros": harga = 12000; break;
                case "sweet corn": harga = 13000; break;
                case "salad buah": harga = 15000; break;
            }
        harga_field.setText("Rp " + harga); 
        }
    }//GEN-LAST:event_list_menuValueChanged


    private void btn_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_totalActionPerformed
       Object selectedMenu = list_menu.getSelectedValue();
       String jumlahPesanan = jumlah_field.getText();
       
       if (selectedMenu !=null && ! jumlahPesanan.isEmpty()){
           try{
               String menu = selectedMenu.toString();
               int jumlah = Integer.parseInt(jumlahPesanan);
               int harga = 0;
               
               switch (menu.toLowerCase()){
                    case "bakso": harga = 15000; break;
                    case "nasi goreng spesial": harga = 20000; break;
                    case "ayam lada hitam": harga = 25000; break;
                    case "ayam bbq": harga = 24000; break;
                    case "ayam mentega": harga = 24000; break;
                    case "americano": harga = 15000; break;
                    case "cappucino": harga = 13000; break;
                    case "lemon tea": harga = 12000; break;
                    case "lemon": harga = 12000; break;
                    case "matcha latte": harga = 12000; break;
                    case "dimsum": harga = 20000; break;
                    case "churros": harga = 12000; break;
                    case "sweet corn": harga = 13000; break;
                    case "salad buah": harga = 15000; break;
               }
               int subTotal = harga*jumlah;
               keranjangPesanan += menu + " (" + jumlah + "x)= Rp " + subTotal + "\n";
               
               totalHarga += subTotal;
               keranjang_field.setText((keranjangPesanan));
               
               total_field.setText("Rp "+totalHarga);
                      
           }catch (NumberFormatException e){
            
            JOptionPane.showMessageDialog(this,"Isi jumlah dengan angka!");
           }
       }
    }//GEN-LAST:event_btn_totalActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        keranjangPesanan = "";
        totalHarga = 0;
        
        keranjang_field.setText("");
        total_field.setText("");
        jumlah_field.setText("");
        harga_field.setText("");
        no_meja_field.setText("");
        pesan_field.setText("");
        
        list_menu.clearSelection();
        
    }//GEN-LAST:event_btn_resetActionPerformed

    private void total_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_fieldActionPerformed

    private void harga_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_fieldActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_total;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dropdown_kategori;
    private javax.swing.JTextField harga_field;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jumlah_field;
    private javax.swing.JTextArea keranjang_field;
    private javax.swing.JList<String> list_menu;
    private javax.swing.JTextField no_meja_field;
    private javax.swing.JButton pesan_button;
    private javax.swing.JTextField pesan_field;
    private javax.swing.JTextField total_field;
    // End of variables declaration//GEN-END:variables
}
